[package]
name = "minireq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimq = "0.5"
heapless = {version = "0.7", features = ["serde"] }
serde-json-core = "0.4"
log = "0.4"
serde = { version = "1", features = ["derive"], default-features = false }
smlang = "0.5"

[dev-dependencies]
std-embedded-nal = "0.1"
std-embedded-time = "0.1"
tokio = { version = "1.9", features = ["rt-multi-thread", "time", "macros"] }
env_logger = "0.9"
